#! /usr/bin/bash
# Create necesary directories
mkdir test/media
mkdir test/static

# Create the conda environment
conda create --name softbutterfly-django-mailauth --file requirements.test.conda -y
source activate softbutterfly-django-mailauth

# Install pip dependendies
pip install -r requirements.test.pip

# Link module directory to the environment library (only for development)
env_path="$(conda info --env | grep softbutterfly-django-mailauth)"
env_path="/${env_path#*/}"

library_path="${env_path}/lib/python3.6/site-packages/"
module_path="$(pwd)/softbutterfly/"

ln -s "${module_path}" "${library_path}"

# Running all the django stuff
source activate softbutterfly-django-mailauth
cd test
python manage.py makemigrations mailauth
python manage.py migrate
python manage.py createsuperuser
python manage.py runserver
